---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: latest

inputs: 
- name: resource-orders

run:
 path: sh
 args:
 - -exc
 - |
    echo "NO TESTS TO RUN"