---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: latest

inputs: 
- name: resource-orders

run:
  dir: resource-orders
  path: dotnet
  args: [build]
